### PR TITLE
Allow date format ordering other than d-m-y

### PR DESCRIPTION
**Pull request by smg6511**
Proposed changes add m-d-y, y-d-m, and y-m-d ordering in the back end renderer and front end snippet (via changes to the main class). Also, getUTC\* functions used in renderer to ensure generated date is zero-hour in any timezone.

### CODE REVIEW

**Comment by Jako** [comment]
Thanks for your pull request. I think about the getUTC functions. Does they regard the MODX date_timezone system settings? https://rtfm.modx.com/revolution/2.x/administering-your-site/settings/system-settings/date_timezone

**Comment by smg6511** [comment]
Thanks for taking a look. Because the _time_ portion of the datetime information is not used in this component and the methods being altered are only for rendering the stored data in a certain format on the front end/in migx, the modx timezone settings would have no bearing on the output anyway. 

The motivation for altering the current code was that I was getting back incorrect dates on the front end (in my case, they were a day ahead because I'm in the U.S.). What's happening in the original code, using a test start date of 2016-02-03, is:
1. On the initial date creation new Date(data[0]), a GMT/UTC datetime is being returned as expected: 
"Tue Feb 02 2016 19:00:00 GMT-0500 (EST)" (Feb 03 2016 00:00:00 minus 5 hours)
2. Using the regular get\* methods on this date object just returns the browser timezone-converted parts of the above date object. But we really need the unconverted (zero-hour) datetime, as getUTC\* methods will give you. You wouldn't see this problem in Europe and East, as the GMT/UTCs are all on the plus side (for instance, in China the conversion would have resulted in "Feb 03 2016 08:00:00 GMT+0800")

Because of the way the **start** variable is used later in the script [in the Ext.util.Format.date() calls], it's easier to just redefine the **start** (and **end**) variable as I've done on lines 32-33 to get a zero-hour date to work with from that point on.

**Comment by Jako** [comment]
I have cherry picked most of your changes and refactored the code a bit. The only thing, that were not accepted are the getUTC functions. Thanks for your work.

**Comment by smg6511** [comment]
Thanks for folding those additions/changes in. I'm curious why you didn't want to use the UTC functions. Did you encounter problems in testing from where you are? Note that in the U.S. the renderer will still return the incorrect day because the time offset here is GMT(UTC)-5 to -8.

**Comment by Jako** [comment]
It is not the right place to fix that issue in my opinion. It should be done in the getlist processor.

**Pull request closed without merging**
